# Generated by Django 2.2.4 on 2021-05-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_decano', models.CharField(help_text='Nombre del Decano', max_length=50, verbose_name='Nombre Decano')),
                ('cedula', models.CharField(help_text='Cedula', max_length=50, verbose_name='Cedula')),
            ],
            options={
                'verbose_name': 'Decano',
                'verbose_name_plural': 'Decano',
                'ordering': ['id'],
            },
        ),
    ]
