# Generated by Django 2.2.4 on 2021-05-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_asig', models.CharField(default='', help_text='Nombre del Docente', max_length=50, verbose_name='Nombre')),
                ('cod_asig', models.CharField(default='', help_text='Apellido del Docente', max_length=50, verbose_name='Apellido')),
                ('num_cred_asig', models.CharField(default='', help_text='Cédula del Docente', max_length=50, verbose_name='Cédula')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignatura',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='decano',
            name='ape_decano',
            field=models.CharField(default='', help_text='Apeliido del Decano', max_length=50, verbose_name='Apeliido'),
        ),
        migrations.AddField(
            model_name='decano',
            name='cel_decano',
            field=models.CharField(default='', help_text='Celular del Decano', max_length=50, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='decano',
            name='cedula',
            field=models.CharField(default='', help_text='Cédula del Decano', max_length=50, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='decano',
            name='nom_decano',
            field=models.CharField(default='', help_text='Nombre del Decano', max_length=50, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_facultad', models.CharField(default='', help_text='Nombre del Facultad', max_length=50, verbose_name='Nombre')),
                ('num_blo_facultad', models.CharField(default='', help_text='Número de bloque de la Facultad', max_length=50, verbose_name='Número de bloque')),
                ('ubi_facultad', models.CharField(default='', help_text='Ubicación de la Facultad', max_length=50, verbose_name='Ubicación')),
                ('decano', models.ForeignKey(default='', help_text='Decano', on_delete=django.db.models.deletion.DO_NOTHING, to='facu.Decano', verbose_name='Decano')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_est', models.CharField(default='', help_text='Nombre del Estudiante', max_length=50, verbose_name='Nombre')),
                ('ape_est', models.CharField(default='', help_text='Apellido del Estudiante', max_length=50, verbose_name='Apellido')),
                ('cc_est', models.CharField(default='', help_text='Cédula del Estudiante', max_length=50, verbose_name='Cédula')),
                ('dir_est', models.CharField(default='', help_text='Dirección de Residencia', max_length=50, verbose_name='Dirección')),
                ('asignatura', models.ForeignKey(default='', help_text='Asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='facu.Asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_docente', models.CharField(default='', help_text='Nombre del Docente', max_length=50, verbose_name='Nombre')),
                ('ape_docente', models.CharField(default='', help_text='Apellido del Docente', max_length=50, verbose_name='Apellido')),
                ('cc_docente', models.CharField(default='', help_text='Cédula del Docente', max_length=50, verbose_name='Cédula')),
                ('titulo_docente', models.CharField(default='', help_text='Titulo del Docente', max_length=50, verbose_name='Titulo')),
                ('facultad', models.ForeignKey(default='', help_text='Facultad', on_delete=django.db.models.deletion.DO_NOTHING, to='facu.Facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docente',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(default='', help_text='Docente', on_delete=django.db.models.deletion.DO_NOTHING, to='facu.Docente', verbose_name='Docente'),
        ),
    ]
