# Generated by Django 2.2.4 on 2021-05-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facu', '0002_auto_20210507_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='decano',
        ),
    ]
