# Generated by Django 2.2.4 on 2021-05-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facu', '0003_remove_facultad_decano'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='decano',
            field=models.ForeignKey(default='', help_text='Decano', on_delete=django.db.models.deletion.DO_NOTHING, to='facu.Decano', verbose_name='Decano'),
        ),
    ]
